services:
  app:
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/notes?authSource=admin
    build: .
    ports:
    - 3000:3000
    container_name: app
    depends_on: 
    - mongodb
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    